(autoload 'el-autoyas-expand-maybe              "el-autoyas" "" t)
(autoload 'el-autoyas-snippet                   "el-autoyas" "" nil)
(autoload 'el-autoyas-text-on-moving-away       "el-autoyas" "" nil)
(autoload 'el-autoyas-update                    "el-autoyas" "" nil)
(provide 'el-autoyas-elisp-epkg-autoloads)
